# Base configuration
permalink: /:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: redcarpet
pygments: true

# Title
name: Open Source Program
subtitle: A set of templates and artifacts to support open source programs 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/open-source-program-template'

# Author/Organization info to be displayed in the templates
author:
  name: T. Jefferson 
  url: http://localhost:4000

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: index.html
  internal: true
- text: Open Source Policy
  url: oss_policy.html
  internal: true
- text: Open Design
  url: open_design.html
  internal: true
- text: FAQs
  url: example_page.html
  internal: true 
- text: Code Flow
  url: example_page.html
  internal: true
- text: Hosting
  url: example_page.html
  internal: true
- text: DOCter Repo
  url: https://github.com/cfpb/DOCter
  internal: false
