# Base configuration
permalink: /news/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown

#Prose.io editing info
repo_name: microsite-template
branch: gh-pages
#GitHub organization name *or* username
gh_org: 18f
prose_url: http://prose.io
site_url: https://pages.18f.gov/Level-Up/
media: assets/img


# Your Programs's Name
name: Level Up
subtitle: Agenda

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/level-up'

# Author/Organization info to be displayed in the templates
author:
  name: Thomas Jefferson 
  url: http://localhost:4000

# ------------------------------------------------------------------
#   Navigation
#   List links that should appear in the site sidebar here
#   "pages" is a directory to keep web content that are not posts
# ------------------------------------------------------------------
navigation:
- text: Home
  url: index.html
  internal: true
- text: Unconference Sessions
  url: pages/unconference.html
  internal: true
- text: Snacky Breakouts 
  url: pages/breakout.html
  internal: true
- text: Lessons Learned
  url: pages/lessons.html
  internal: true

