org_name:  YOUR ORGANIZATION NAME
street: 1000 Main Street
suite: 
city: Washington
state: D.C.
zip: 20000
point_of_contact:  George Mason <george.mason@gunstonhall>
sponsoring_office: Office of the Chief Information Officer

